---
# roles/win_update/tasks/
- name: create temp folder
  ansible.windows.win_file:
    path: "{{ ansible_temp }}"
    state: directory

- name: List files in temp
  ansible.windows.win_powershell:
    script: |
      Get-ChildItem "{{ ansible_temp }}" | Out-String -Stream
  register: cmd_out
  changed_when: False
  failed_when: "cmd_out.error | length != 0"

- name: File List
  ansible.builtin.debug:
    var: cmd_out

- name: Search and download windows update without installing them
  ansible.windows.win_updates:
    state: installed
    log_path: "{{ ansible_temp }}\\ansible_win_updates.txt"

- name: copy powershell profile
  ansible.windows.win_copy:
    src: powershell_profile.ps1
    dest: "{{ item }}"
  with_items:
    - '%USERPROFILE%\Documents\WindowsPowershell\Microsoft.PowerShell_profile.ps1'
    - '%USERPROFILE%\Documents\Powershell\Microsoft.VSCode_profile.ps1'
