---
# roles/wsl/tasks/
# prepare WSL before connecting

- import_tasks: next_apt.yml

- name: Change default editor to micro
  lineinfile:
    path: "/home/infinite4ever/.profile"
    regexp: '^export EDITOR='
    line: 'export EDITOR=/usr/bin/micro'
